#单节点
#应用名称及验证账号
#server:
#  port: 7900
spring:
  application:
    name: eureka
#security:
#  user:
#    name: root
#    password: root
eureka:
  instance:
    hostname: eureka-7900
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:7900/eureka/,http://localhost:7901/eureka/,http://localhost:7902/eureka/

server:
  port: 7900